name: Deploy Backend

on:
    push:
        branches:
            - main
        paths:
            - "backend/**"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Check out code
              uses: actions/checkout@v4

            - name: Deploy
              uses: akhileshns/heroku-deploy@v3.13.15
              with:
                  heroku_api_key: ${{secrets.HEROKU_API_KEY}}
                  heroku_app_name: "node-ec-app"
                  heroku_email: ${{secrets.HEROKU_EMAIL}}
                  usedocker: false
