name: Deploy Backend

on:
    push:
        branches:
            - main
        paths:
            - "backend/**"

jobs:
    deploy:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Cache Docker layers
              uses: actions/cache@v2
              with:
                  path: /tmp/.buildx-cache
                  key: ${{ runner.os }}-buildx-${{ github.sha }}
                  restore-keys: |
                      ${{ runner.os }}-buildx-

            - name: Log in to Heroku Container Registry
              run: |
                  echo ${{ secrets.HEROKU_API_KEY }} | docker login --username=_ --password-stdin registry.heroku.com

            # - name: Log in to Docker Hub
            #   uses: docker/login-action@v2
            #   with:
            #       username: ${{ secrets.DOCKER_USERNAME }}
            #       password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build Docker image
              uses: docker/build-push-action@v3
              with:
                  context: .
                  file: ./backend/Dockerfile # Dockerfileのパスを指定
                  push: true
                  tags: registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web:latest
                  provenance: false
              env:
                  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
                  HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}

            - name: Log in to Heroku
              uses: akhileshns/heroku-deploy@v3.12.12
              with:
                  heroku_api_key: ${{secrets.HEROKU_API_KEY}}
                  heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
                  heroku_email: ${{secrets.HEROKU_EMAIL}}
                  buildpack: "https://github.com/lstoll/heroku-buildpack-monorepo.git,heroku/gradle" # 必要に応じて変更
                  usedocker: true
                  dockerfile_path: ./backend
                  process_type: web
