name: Deploy Backend

on:
    push:
        branches:
            - main
        paths:
            - "backend/**"

jobs:
    deploy:
        runs-on: ubuntu-22.04
        # 複数のDockerfileが配置されたディレクトリを列挙
        strategy:
            matrix:
                target: ["backend"]
    steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1

        - name: Log in to the Container registry
          uses: docker/login-action@v1
          with:
              registry: ghcr.io
              username: ${{ github.repository_owner }}
              password: ${{ secrets.GITHUB_TOKEN }}

        - name: Set image tag for master
          if: github.ref == 'refs/heads/master'
          run: |
              COMMITID=$(git rev-parse --short ${{ github.sha }})
              echo "DOCKER_TAG=master-${COMMITID}" >> $GITHUB_ENV

        # 並列でContainer Imageをビルド
        - name: Build and push Docker image
          uses: docker/build-push-action@v2
          with:
              context: ./${{ matrix.target }}
              push: true
              tags: ghcr.io/cdsl-research/${{ matrix.target }}:${{ env.DOCKER_TAG }}
        - uses: actions/checkout@v2
        - uses: akhileshns/heroku-deploy@v3.7.8
          with:
              heroku_api_key: ${{secrets.HEROKU_API_KEY}}
              heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
              heroku_email: ${{secrets.HEROKU_EMAIL}}
              buildpack: "https://github.com/lstoll/heroku-buildpack-monorepo.git,heroku/gradle" # 必要に応じて変更
              usedocker: true
