name: Deploy Backend

on:
    push:
        branches:
            - main
        paths:
            - "backend/**"

jobs:
    deploy:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v2

            - name: Build Docker image
              uses: docker/build-push-action@v3
              with:
                  context: .
                  file: ./backend/Dockerfile # Dockerfileのパスを指定
                  push: false
                  tags: user/image:latest

            - uses: akhileshns/heroku-deploy@v3.12.12
              with:
                  heroku_api_key: ${{secrets.HEROKU_API_KEY}}
                  heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
                  heroku_email: ${{secrets.HEROKU_EMAIL}}
                  buildpack: "https://github.com/lstoll/heroku-buildpack-monorepo.git,heroku/gradle" # 必要に応じて変更
                  usedocker: true
