name: Deploy Backend

on:
    push:
        branches:
            - main
        paths:
            - "backend/**"

jobs:
    docker:
        web: backend/Dockerfile
    deploy:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v2
            - uses: akhileshns/heroku-deploy@v3.7.8
              with:
                  heroku_api_key: ${{secrets.HEROKU_API_KEY}}
                  heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
                  heroku_email: ${{secrets.HEROKU_EMAIL}}
                  buildpack: "https://github.com/lstoll/heroku-buildpack-monorepo.git,heroku/gradle" # 必要に応じて変更
                  usedocker: true
