name: Deploy

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install Heroku CLI # <- IMPORTANT!!! Make sure the cli is installed before using the action
              run: |
                  curl https://cli-assets.heroku.com/install.sh | sh
            - uses: akhileshns/heroku-deploy@v3.12.12
              with:
                  heroku_api_key: ${{secrets.HEROKU_API_KEY}}
                  heroku_app_name: "node-ec-app"
                  heroku_email: "hnaoya1120@gmail.com"
                  usedocker: true
