name: Deploy

run: |
    curl https://cli-assets.heroku.com/install.sh | sh

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: akhileshns/heroku-deploy@v3.12.12
              with:
                  heroku_api_key: "HRKU-f6e91d63-46b8-4d24-9b27-908cf1fa64b6"
                  heroku_app_name: "node-ec-app"
                  heroku_email: "hnaoya1120@gmail.com"
                  usedocker: true
